### ISSUE TITLE
[CI] Workflows take too long to complete

### ISSUE THREAD

**Issue by ubgk** [upkie/vulp#46]
In our current setup, workflows take too long to finish.

We should check what can be cached across builds to speed up the process.

**Comment by stephane-caron** [comment]
Workflows do take time :sweat_smile: I haven't felt the need to speed them up so far, since with Bazel we can run them locally, and there hadn't been many cases where a workflow would fail remotely but not locally (well, currently there's one with `clang-format`...).

I agree we could use some caching :+1: As long as it doesn't break local workflows (nor adds too much extra complexity) it sounds like a net productivity improvement.

**Comment by pgraverdy** [comment]
I tested on my side for the CI workflow and I can get workflows to have workflow finish 50% faster using caches
- using cache per job and branch/PR (with keys) 
- currently runs only on PR into main
- first run in PR still takes 4 minutes

Check https://github.com/pgraverdy/upkie/actions (CI job #42 vs #41)

@ubgk What was the issue with the other PR ?

**Comment by stephane-caron** [comment]
Closing this issue as of archiving this project. Feel free to continue the discussion in [upkie](https://github.com/upkie/upkie) if new elements come to light!
